package com.test.mylifegoale.utilities;

import java.text.SimpleDateFormat;
import java.util.Locale;

public class Constants {
    public static final String APP_DB_NAME = "myAffirmation.db";
    public static final String BUNDLE_OBJECT = "DataObject";
    public static final SimpleDateFormat DATE_FORMAT_DATE_DB = new SimpleDateFormat("yyyy/MM/dd");
    public static final String DB_BACKUP_DIRECTORY = "MyLifeGoal";
    public static final String DEFAULT_AFFIRMATION_TEXT = "I’m committing myself to live a happy life.";
    public static final String DELETE_DATA = "Delete_Data";
    public static final String DELETE_VISION_TAG = "DELETE_VISION_TAG";
    public static final String Data_Changed = "Data_Changed";
    public static final String EDIT_ADD_VISION_TAG = "IS_EDITED";
    public static final SimpleDateFormat FILE_DATE_FORMAT = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
    public static final String FOLDER_COLOR_TYPE_Abundance = "#f88c8c";
    public static final String FOLDER_COLOR_TYPE_Attitude = "#8cdbf9";
    public static final String FOLDER_COLOR_TYPE_Beauty = "#288ea1";
    public static final String FOLDER_COLOR_TYPE_Business = "#f69fd6";
    public static final String FOLDER_COLOR_TYPE_Decision_Making = "#bca1f2";
    public static final String FOLDER_COLOR_TYPE_Exercise = "#86bafb";
    public static final String FOLDER_COLOR_TYPE_Family = "#70a0be";
    public static final String FOLDER_COLOR_TYPE_Forgiveness = "#8c9bd5";
    public static final String FOLDER_COLOR_TYPE_Gratitude = "#a0d69a";
    public static final String FOLDER_COLOR_TYPE_Health = "#91d0c7";
    public static final String FOLDER_COLOR_TYPE_Law_of_attraction = "#a0be70";
    public static final String FOLDER_COLOR_TYPE_Love = "#ffbb94";
    public static final String FOLDER_COLOR_TYPE_Pregnancy = "#c1c962";
    public static final String FOLDER_COLOR_TYPE_Relationship = "#997fbc";
    public static final String FOLDER_COLOR_TYPE_Self_Esteem = "#8786fb";
    public static final String FOLDER_COLOR_TYPE_Success = "#fda88b";
    public static final String FOLDER_COLOR_TYPE_Women = "#c96262";
    public static final String FOLDER_IMAGE_TYPE_Abundance = "Abundance";
    public static final String FOLDER_IMAGE_TYPE_Attitude = "Attitude";
    public static final String FOLDER_IMAGE_TYPE_Beauty = "Beauty";
    public static final String FOLDER_IMAGE_TYPE_Business = "Business";
    public static final String FOLDER_IMAGE_TYPE_CREATIVITY = "Creativity";
    public static final String FOLDER_IMAGE_TYPE_Confidence = "Confidence";
    public static final String FOLDER_IMAGE_TYPE_Decision_Making = "Decision Making";
    public static final String FOLDER_IMAGE_TYPE_Exercise = "Exercise";
    public static final String FOLDER_IMAGE_TYPE_Family = "Family";
    public static final String FOLDER_IMAGE_TYPE_Forgiveness = "Forgiveness";
    public static final String FOLDER_IMAGE_TYPE_Gratitude = "Gratitude";
    public static final String FOLDER_IMAGE_TYPE_Law_of_attraction = "Law of attraction";
    public static final String FOLDER_IMAGE_TYPE_Love = "Love";
    public static final String FOLDER_IMAGE_TYPE_POSITIVE_THINKING = "Positive Thinking";
    public static final String FOLDER_IMAGE_TYPE_PUBLIC_SPEAKING = "Public Speaking";
    public static final String FOLDER_IMAGE_TYPE_Pregnancy = "Pregnancy";
    public static final String FOLDER_IMAGE_TYPE_Relationship = "Relationship";
    public static final String FOLDER_IMAGE_TYPE_Self_Esteem = "Self Esteem";
    public static final String FOLDER_IMAGE_TYPE_WEALTH = "Wealth";
    public static final String FOLDER_IMAGE_TYPE_WEIGHT_LOSS = "Weight loss";
    public static final String FOLDER_IMAGE_TYPE_Women = "Women";
    public static final String INTENT_KEY = "Status";
    public static final String PATH_ASSET = "file:///android_asset/";
    public static final String PATH_BG_MUSIC = "/Affirmation Background Music";
    public static final String PATH_BG_VOICE = "/Affirmation Background Voice";
    public static final String PATH_IMAGE = "/Affirmation Images";
    public static final String PATH_RESOURCE = "android.resource://";
    public static final String PATH_SOUND = "/Affirmation Sound";
    public static final String RATTING_BAR_TITLE = "How was your experience with us?";
    public static final int REQUEST_CODE_ALARM_ID = 11104;
    public static final String REQUEST_CODE_ALARM_NAME = "REQUEST_CODE_ALARM_NAME";
    public static final String REQUEST_CODE_ALARM_NAME_ID = "REQUEST_CODE_ALARM_NAME_ID";
    public static final int REQUEST_CODE_REMIND_24 = 1124;
    public static final int REQUEST_CODE_REMIND_3 = 1103;
    public static final int REQUEST_CODE_SET_ALARM = 1111;
    public static final int REQUEST_CODE_SIGN_IN = 1005;
    public static final int REQUEST_PERM_AUDIO = 1052;
    public static final int REQUEST_PERM_BACKUPFILE = 1055;
    public static final int REQUEST_PERM_FILE = 1051;
    public static final int REQUEST_PICK_IMAGE = 1101;
    static final Locale locale = Locale.getDefault();

    public static final SimpleDateFormat SIMPLE_MONTH_YEAR = new SimpleDateFormat("MMM, yyyy", locale);
    public static final SimpleDateFormat SIMPLE_DATE = new SimpleDateFormat("MMM dd, yyyy", locale);
    public static final SimpleDateFormat SIMPLE_DATE_FORMAT_ALL = new SimpleDateFormat("EEE, dd MMM yyyy hh:mm a", locale);
    public static final SimpleDateFormat SIMPLE_DATE_FORMAT_DATE_TIME = new SimpleDateFormat("dd MM yyyy HH:mm:ss.SSS");
    public static final SimpleDateFormat SIMPLE_Month_year_DATE = new SimpleDateFormat("MMM, dd", locale);
    public static final SimpleDateFormat SIMPLE_TIME_OF_MONTH = new SimpleDateFormat("hh:mm a", locale);
    public static final String VISION_DATA_TAG = "VISION_DATA_TAG";
    public static String my_goals = "List of personal goals...";
    public static String my_vision = "What you envision yourself to be at in the future...";
    public static String your_purpose = "Your purpose in life...";
}
